# Generated by Django 3.1 on 2020-08-16 08:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InputResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_data', models.TextField()),
                ('result', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='DeleteDuplicates',
            fields=[
                ('inputresult_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='tools.inputresult')),
                ('case_sensitive', models.BooleanField(default=False)),
                ('save_position', models.BooleanField(default=False)),
            ],
            bases=('tools.inputresult',),
        ),
        migrations.CreateModel(
            name='NumbersInWords',
            fields=[
                ('inputresult_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='tools.inputresult')),
            ],
            bases=('tools.inputresult',),
        ),
        migrations.CreateModel(
            name='RowToColumn',
            fields=[
                ('inputresult_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='tools.inputresult')),
                ('sep', models.CharField(max_length=10)),
            ],
            bases=('tools.inputresult',),
        ),
        migrations.CreateModel(
            name='ColumnToRow',
            fields=[
                ('rowtocolumn_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='tools.rowtocolumn')),
            ],
            bases=('tools.rowtocolumn',),
        ),
    ]
