# Generated by Django 3.1 on 2020-08-25 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0002_listsorting'),
    ]

    operations = [
        migrations.AddField(
            model_name='listsorting',
            name='case_sensitive',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='listsorting',
            name='save_position',
            field=models.BooleanField(default=False),
        ),
    ]
