# Generated by Django 3.1 on 2020-08-28 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0004_changecase'),
    ]

    operations = [
        migrations.AddField(
            model_name='changecase',
            name='mode',
            field=models.CharField(choices=[('each_word', 'Каждое Слово / кАЖДОЕ сЛОВО'), ('sentence', 'Как. В предложении'), ('all_letters', 'ВСЕ БУКВЫ / все буквы'), ('fence', 'ЗаБоРчИкОм'), ('random_case', 'сЛуЧАЙныЙ РЕГиСТр')], default='each_word', max_length=50),
        ),
        migrations.AddField(
            model_name='changecase',
            name='option_force',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='changecase',
            name='option_reverse',
            field=models.BooleanField(default=False),
        ),
    ]
