# Generated by Django 3.1 on 2020-08-31 10:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0006_autofill'),
    ]

    operations = [
        migrations.CreateModel(
            name='CrossMinusCleaner',
            fields=[
                ('inputresult_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='tools.inputresult')),
            ],
            bases=('tools.inputresult',),
        ),
        migrations.RenameField(
            model_name='deleteduplicates',
            old_name='save_position',
            new_name='delete_nulls',
        ),
    ]
