# Generated by Django 3.1 on 2020-08-31 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0007_auto_20200831_1543'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listsorting',
            old_name='save_position',
            new_name='reverse',
        ),
    ]
