# Generated by Django 3.1 on 2020-08-31 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0008_auto_20200831_1544'),
    ]

    operations = [
        migrations.AddField(
            model_name='crossminuscleaner',
            name='delete_nulls',
            field=models.BooleanField(default=False),
        ),
    ]
