# Generated by Django 3.1 on 2020-08-31 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0009_crossminuscleaner_delete_nulls'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crossminuscleaner',
            name='delete_nulls',
        ),
    ]
